# Chap 27 : ARC

- Reference type 
    - 하나의 인스턴스가 참조를 통해 여러 곳에서 접근
    - 따라서 메모리 해제 언제인지 (when) 중요
    - 메모리 자원 이슈, 성능 이슈 관련

## 📝 ARC (Automatic Reference Counting)
- 자동으로 메모리 관리 (필요없는 클래스의 인스턴스 메모리 해제)
- <i> compile 시 참조를 계산함 </i>
- 참조횟수 == 0 : 메모리에서 해제

## 📝 강한 참조 (Strong Reference)
- 인스턴스야 너는 계속 메모리에 남아있거라
- 강한 참조 사용시 : +1
- nil 할당 : -1

## 📝 강한 참조 (Strong Reference) 순환 문제
- 2개의 클래스 인스턴스가 서로 참조하는 경우
- reference cnt !=0 -> 메모리 해제 불가

## 📝 약한 참조 (Weak Reference)
- 변수 선언 할 때 `weak` 를 붙여
- 해제시 `nil` 이 될 수 있으므로 `let` 불가
- 말인즉슨 늘 옵셔널이어야함

## 📝 미소유 참조 (Unowned Reference)
- 인스턴스의 수명이 동일할때
- 값이 늘 있어야 하므로 옵셔널/변수가 아니여도 됨

# Chap 28 : 오류처리

## 📝 함수에서 오류 발생
- `throws` 오류를 던져 : 메소드 옆에
- `throw` 오류를 던져 : 오류가 발생할 구간에
- `guard` 문을 써서 오류 발생의 여지를 준다?
- `try` 오류를 처리 1
    - 오류가 발생할 텐데 한번 시도는 해볼게!!
-  `do catch` 오류를 처리 2


## 📝 코드 시나리오 
[reference](https://twih1203.medium.com/swift-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC-throws-do-catch-try-%ED%95%98%EA%B8%B0-c0f320e61f62)
```swift
func printNumber(_ number: Int) throws -> Int {    
   var text = ""
  
   guard number > 0 else {
   throw TestError.outOfRange                
   }
   return text
}

```

- 여기서 만약 음수를 파라미터로 넘긴다면 -> 당연히 오류
- `try` 를 쓰자

```swift
let resultNumber = try object.printNumber(-20)
```

- 꼭 `do catch` 도 써줘!!

```swift
do {
   let resultNumber = try object.printNumber(-20)
} catch {
   
   print(error)
}
```

- 오류는 꼭 정의 안해도됨
- `catch` 도 생략 가능
- `enum` 으로 오류 케이스 나누는 것도 가능

# 📝 try? vs. try!
- try?
    - 그래, 오류가 발생할주도 있는 거 ㅇㅈ
    - 옵셔널과 비슷해보이지? 맞아!!
- try!
    - 응 절대 오류 안나
    - 오류나면 강제종료